### PR TITLE
009: add tangles origin

### PR DESCRIPTION
**Pull request by mixmix**

### CODE REVIEW

**Comment by staltz** [comment]
It seems like this new section either belongs to the `Motivation` section, or then it belongs to https://dev.scuttlebutt.nz/

**Comment by mixmix** [comment]
I want it recorded somewhere, wasn't sure so formatted it and dropped it in.

I think I want it in this sip because people seem to struggle with how previous field works but I think this makes it clearer

**Comment by staltz** [comment]
How about putting it outside of the SIP but then linking it here as an informative reference?

I think there is value in SIPs being concise and focused at how to implement (or be compliant with) them.

**Comment by mixmix** [comment]
Counter-proposal, keep it in this repo, but put it in a folder and link to it.
That way if a person clones this down they still get this useful info which might help them better understand

**Comment by staltz** [comment]
Works for me. Feel free to merge this (to `tangles`, not `master`)

**Pull request merged**
