### PR TITLE
add BIPF to the SIPS series

### PR DESCRIPTION
**Pull request by tschudin**
This is about BIPF as used in tinySSB, also explains BIPF.classic from arj03+gpicron, and has a comprehensive reference list.
greetings, cft

### CODE REVIEW

**Comment by staltz** [comment]
Nice! Give me some time to review and it should be merged soon enough.

**Review by staltz — APPROVED** [review]
Looks good to me, I focused my attention on reading the text and following the ideas. I haven't validated whether all the example fixtures and (pseudo)code are correct.

If no one else adds to this review, I can merge by the end of this week.

**Comment by staltz** [comment]
I will give it a number after merging.

Thanks!

**Comment by tschudin** [comment]
thanks you, @staltz !

**Pull request merged**
