### PR TITLE
more typos

### PR DESCRIPTION
**Pull request by cmoid**
sorry I should bundle these and push them en masse. I'm implementing this spec as an elixir exercise and reading it closely. 

As an aside, the reference python implementation has some missing links and the distribution leaves out some test codes also mentioned.

### CODE REVIEW

**Comment by staltz** [comment]
I'm not sure I understand the addition of the `BYTES_VAL` and whether it's a breaking change (if someone were to follow the spec strictly and blindly), so I'll defer to @tschudin .

**Comment by cmoid** [comment]
oops, I misread that. I had done pattern recognition on the two and thought it missing :)

I'll resubmit the other typo when I push up my implementation, in case I find more.

**Comment by tschudin** [comment]
@cmoid : Please note that I do not see or get notified about some PRs or discussions you had, good that @staltz referenced my handle in the comment. Great that an independent implementation is coming, and thanks for the typo fixes!

BTW: for the ESP32 side of tinySSB I now also have a C++ implementation, if that is helpful. See [https://github.com/ssbc/tinySSB/blob/main/esp32/loramesh-TBeam/bipf.cpp](https://github.com/ssbc/tinySSB/blob/main/esp32/loramesh-TBeam/bipf.cpp)

**Comment by gpicron** [comment]
@tschudin 

- the link to the github repo of the python reference impl is broken at https://pypi.org/project/bipf/
- the nim implementation can also be used on esp32 (I'm making some tests together with https://github.com/elcritch/nesper
- I proposed similar change for the ints for the original BIPF spec https://github.com/ssbc/bipf-spec/issues/1 .  The main difference was that I proposed a zigzag encoding of int before keeping only the most significant bytes.  Actually this is because I made some stats on existing content of SSB and there is quite a lot of "-1" encoded (negative votes) and simply keeping the most significant bytes in that cases mean 8 bytes...
- A change on the original BIPF was recently merged https://github.com/ssbc/bipf-spec/pull/3.  It converts the BOOLNULL field to ATOM, allowing applications to use value 3, 4, 5 to encode application specific "value" known by it.  The primary use was to compress further the on-disk storage of entries in BIPF using key dictionaries and value dictionaries in the context of SSB-Archive (which I abandonned as it does not make sense anymore with pppp).  But now I'm using it in the com between some ESP32 using session hash table like in Erlang OTP network.  I think you may find some use of it for tinySSB

**Pull request closed without merging**
